apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec"
      - "services"
      - "endpoints"
      - "configmaps"
      - "persistentvolumeclaims"
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]
  - apiGroups: [""]
    resources:
      - "secrets"
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "replicasets"
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]
  - apiGroups: [""]
    resources:
      - "events"
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources:
      - "jobs"
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: airflow-service-account
    namespace: default
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io
